### ISSUE TITLE
jumping to an anchor (title) in a page, the destination is cvered by the top menu

### ISSUE THREAD

**Issue by gggina** [magneticio/revamp.io#168]
![screen shot 2016-10-11 at 12 45 32](https://cloud.githubusercontent.com/assets/3646450/19267737/b843a554-8fb0-11e6-98e6-8e38e9d8d64f.png)

**Comment by gggina** [comment]
this doesn't happen if you click a link from within a page e.g. http://localhost:1313/documentation/installation/set-container-driver/

**Comment by olafmol** [comment]
confirmed. Anchor should be added to browser URL for easy copy&pasting

**Comment by olafmol** [comment]
additionally, when pasting an anchor in a URL the page currently doesn't scroll to the specific anchor. This should be fixed.

**Comment by gggina** [comment]
Still not working, for example https://magneticio.github.io/revamp.io/documentation/how-vamp-works/what-to-choose/#working-with-big-data
